export const drediPages = [
  {
    "id": 380,
    "slug": "proteses",
    "title": "Proteses",
    "link": "https://dredi.com.br/proteses/",
    "headings": [
      "Recupere seu sorriso e sua confiança com uma prótese dentária de alta qualidade!",
      "Recupere seu sorriso e sua confiança com uma prótese dentária de alta qualidade!",
      "Se você sente o impacto da falta de um sorriso...",
      "Volte a sorrir sem medo e sem limitações",
      "Conheça nossos tipos de próteses dentárias:",
      "Histórias reais de transformação",
      "Confira os Depoimentos:",
      "Por que escolher nossas próteses?",
      "Aparência natural e harmônica",
      "Ajuste perfeito para conforto total",
      "Melhoria na mastigação e na fala",
      "Aumento da autoestima e confiança",
      "Materiais de alta qualidade e durabilidade",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Não deixe que a falta de um sorriso completo limite sua vida.",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero transformar meu sorriso"
    ],
    "text": [
      "Recupere seu sorriso e sua confiança com uma prótese dentária de alta qualidade!",
      "Comer, sorrir e falar sem preocupações é possível. Descubra como uma prótese pode transformar sua vida.",
      "Quero transformar meu sorriso",
      "Se você sente o impacto da falta de um sorriso...",
      "Percebe que acaba tendo muitos prejuízos com isso.",
      "Afeta sua autoestima",
      "Sua segurança ao falar",
      "Sua saúde bucal",
      "Dificuldades para mastigar",
      "Vergonha ao sorrir",
      "E várias outras limitações no dia a dia",
      "Não permita que nada disso te impeça de viver plenamente. Você merece um sorriso que traga conforto e confiança!",
      "Volte a sorrir sem medo e sem limitações",
      "Imagine poder comer o que quiser sem medo, sorrir livremente e recuperar sua autoconfiança.",
      "Com uma prótese dentária bem ajustada e natural, você pode voltar a viver sem limitações.",
      "Não se trata apenas de dentes, mas de qualidade de vida e bem-estar.",
      "Conheça nossos tipos de próteses dentárias:",
      "Prótese Fixa Unitária: Para quem perdeu apenas um dente. Reabilitação com aparência natural.",
      "Prótese Fixa Múltipla: Para perdas múltiplas, com estabilidade e estética.",
      "Prótese Total (PT): Solução completa para quem perdeu todos os dentes. Devolva sua função mastigatória e estética.",
      "Prótese Parcial Removível (PPR): Indicada para quem ainda possui alguns dentes. Solução segura e confortável.",
      "Prótese Protocolo: Prótese fixa sobre implantes, ideal para substituição completa dos dentes.",
      "Histórias reais de transformação",
      "Nossos pacientes já passaram por essa jornada e hoje são prova de que é possível ter um sorriso bonito e funcional novamente.",
      "Confira os Depoimentos:",
      "A satisfação dos nossos pacientes é nossa motivação.",
      "Por que escolher nossas próteses?",
      "Aparência natural e harmônica",
      "Soluções sob medida, com estética natural, respeitando a fisionomia exclusiva de cada paciente.",
      "Ajuste perfeito para conforto total",
      "Oferecemos suporte completo para que você tenha uma experiência tranquila e sem preocupações.",
      "Melhoria na mastigação e na fala",
      "Resultados incríveis para uma mastigação mais confortável e uma fala mais eloquente.",
      "Aumento da autoestima e confiança",
      "Sinta-se bem consigo mesmo(a) novamente resgatando e valorizando seu cartão de visitas pessoal: seu sorriso!",
      "Materiais de alta qualidade e durabilidade",
      "Utilizamos tecnologia de ponta com as mais recentes inovações para resultados duradouros.",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Não deixe que a falta de um sorriso completo limite sua vida.",
      "Agende uma avaliação gratuita e descubra a melhor solução para você.",
      "Perguntas Frequentes",
      "Quanto tempo leva para fazer uma prótese dentária??",
      "O tempo varia conforme o tipo de prótese, mas normalmente o processo leva algumas semanas.",
      "A prótese fica natural??",
      "Sim, utilizamos materiais modernos que garantem um resultado estético e funcional.",
      "A prótese é desconfortável?",
      "Inicialmente pode haver um período de adaptação, mas garantimos um ajuste perfeito para seu conforto.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/01/1-300x300.webp",
      "/site-assets/2025/01/2-300x300.webp",
      "/site-assets/2025/01/3-300x300.webp",
      "/site-assets/2025/01/4-300x300.webp",
      "/site-assets/2025/01/5-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-1-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-2-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-3-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-4-300x300.webp",
      "/site-assets/2025/01/Sorriso-perfeito-1024x1024.webp",
      "/site-assets/2025/01/Sorriso-perfeito-150x150.webp",
      "/site-assets/2025/01/Sorriso-perfeito-300x300.webp",
      "/site-assets/2025/01/Sorriso-perfeito-768x768.webp",
      "/site-assets/2025/01/Sorriso-perfeito.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/03/Protese-300x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 883,
    "slug": "clareamento",
    "title": "Clareamento",
    "link": "https://dredi.com.br/clareamento/",
    "headings": [
      "Recupere o brilho do seu sorriso com um clareamento profissional e seguro!",
      "Recupere o brilho do seu sorriso com um clareamento profissional e seguro!",
      "Por que escolher investir no\nclareamento dentário?",
      "Elimina manchas",
      "Preserva os dentes",
      "Empodere-se",
      "Rápido e seguro",
      "O que torna o clareamento do Dr. Edi diferente?",
      "Por que escolher investir no clareamento dentário?",
      "Elimina manchas",
      "Preserva os dentes",
      "Empodere-se",
      "Rápido e seguro",
      "O que torna o clareamento do Dr. Edi diferente?",
      "Para quem o clareamento dentário é indicado?",
      "Para quem sente que seus dentes estão manchados ou amarelados",
      "Para quem deseja um sorriso mais branco sem prejudicar a estrutura natural dos dentes",
      "Para quem quer aumentar a confiança e se sentir melhor ao sorrir",
      "Para quem tem um evento especial e deseja um sorriso impecável",
      "Sorrisos transformados que passaram por nossas mãos",
      "Confira os Depoimentos:",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Seu novo sorriso começa agora!",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero dentes mais brancos"
    ],
    "text": [
      "Recupere o brilho do seu sorriso com um clareamento profissional e seguro!",
      "Já imaginou se olhar no espelho e ver um sorriso mais branco, saudável e confiante? O clareamento dentário é o primeiro passo para transformar sua autoestima e realçar a beleza do seu sorriso.",
      "Quero dentes mais brancos",
      "Você já se olhou no espelho e sentiu que seus dentes não são tão brancos quanto gostaria? Manchas, amarelamento e aquele tom escurecido podem afetar não só a aparência, mas também sua confiança ao sorrir.",
      "A boa notícia? O sorriso que você deseja está ao seu alcance!",
      "Com o clareamento dentário profissional, você pode conquistar dentes mais brancos, saudáveis e radiantes de forma segura e com resultados duradouros.",
      "Por que escolher investir no",
      "clareamento dentário?",
      "Elimina manchas",
      "Elimina manchas e amarelados causados por café, vinho, cigarro e outros alimentos.",
      "Preserva os dentes",
      "Preserva a saúde do esmalte dentário, sem desgastar os dentes.",
      "Empodere-se",
      "Realça sua beleza natural, proporcionando um sorriso mais jovem e vibrante.",
      "Rápido e seguro",
      "Procedimento rápido e seguro, com acompanhamento profissional.",
      "O que torna o clareamento do Dr. Edi diferente?",
      "O Dr. Edi e sua equipe oferecem um tratamento personalizado, seguro e eficaz, utilizando as melhores técnicas do mercado para garantir um resultado natural e duradouro.",
      "Tecnologia de ponta: para um clareamento uniforme e sem sensibilidade excessiva",
      "Opções personalizadas: escolha entre clareamento a laser, caseiro ou combinado para um clareamento uniforme e sem sensibilidade excessiva",
      "Acompanhamento especializado: para garantir um sorriso branco por mais tempo.",
      "Resultado visível já nas primeiras sessões: sem comprometer a estrutura dos dentes.",
      "Por que escolher investir no clareamento dentário?",
      "Tecnologia de ponta: para um clareamento uniforme e sem sensibilidade excessiva.",
      "Opções personalizadas: escolha entre clareamento a laser, caseiro ou combinado para um clareamento uniforme e sem sensibilidade excessiva.",
      "Para quem o clareamento dentário é indicado?",
      "Para quem sente que seus dentes estão manchados ou amarelados",
      "Para quem deseja um sorriso mais branco sem prejudicar a estrutura natural dos dentes",
      "Para quem quer aumentar a confiança e se sentir melhor ao sorrir",
      "Para quem tem um evento especial e deseja um sorriso impecável",
      "Sorrisos transformados que passaram por nossas mãos",
      "Nossos pacientes já passaram por essa jornada e hoje são prova de que é possível ter um sorriso bonito e funcional novamente.",
      "Confira os Depoimentos:",
      "A satisfação dos nossos pacientes é nossa motivação.",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Seu novo sorriso começa agora!",
      "Não deixe para depois a chance de se sentir mais confiante e feliz com seu sorriso. As vagas são limitadas!",
      "Agende sua avaliação e descubra como podemos transformar seu sorriso de forma segura, eficiente e duradoura.",
      "Perguntas Frequentes",
      "O clareamento enfraquece os dentes?",
      "Não! O tratamento profissional é seguro e não desgasta a estrutura dentária.",
      "Vou sentir sensibilidade?",
      "Alguns pacientes podem sentir um leve desconforto temporário, mas utilizamos técnicas que reduzem esse efeito ao máximo.",
      "Quanto tempo dura o clareamento?",
      "Com os cuidados adequados, seu sorriso pode permanecer branco por anos!",
      "Posso fazer o procedimento mais de uma vez?",
      "Sim! O clareamento pode ser refeito conforme a necessidade, sempre com acompanhamento profissional.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/02/1-1-300x300.webp",
      "/site-assets/2025/02/2-1-300x300.webp",
      "/site-assets/2025/02/3-1-300x300.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Clareamento-4-300x300.webp",
      "/site-assets/2025/03/Design-sem-nome-10-300x300.webp",
      "/site-assets/2025/03/Design-sem-nome-12-300x300.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 1194,
    "slug": "dentistica",
    "title": "Dentística",
    "link": "https://dredi.com.br/dentistica/",
    "headings": [
      "Chegou a sua hora de ter dentes perfeitos: elimine manchas, fraturas e imperfeições do seu sorriso!",
      "Chegou sua hora de ter dentes perfeitos: elimine manchas, fraturas e imperfeições do seu sorriso!",
      "O que é dentística?",
      "Estes são os principais tratamentos de dentística:",
      "Restaurações estéticas",
      "Clareamento dentário",
      "Fechamento de diastemas",
      "Facetas de resina ou porcelana",
      "Por que escolher o Dr. Edi e sua equipe?",
      "Por que escolher o Dr. Edi e sua equipe?",
      "Para quem a dentística é indicada?",
      "Para quem deseja corrigir manchas e amarelados nos dentes",
      "Para quem tem pequenas fraturas ou desgastes nos dentes",
      "Para quem busca melhorar o formato e o alinhamento do sorriso",
      "Para quem deseja fechar pequenos espaços entre os dentes (diastemas)",
      "Para quem quer transformar o sorriso de forma rápida e eficaz",
      "Sorrisos transformados que passaram por nossas mãos",
      "Confira os Depoimentos:",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Garanta seu novo sorriso agora!",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero melhorar meu sorriso"
    ],
    "text": [
      "Chegou a sua hora de ter dentes perfeitos: elimine manchas, fraturas e imperfeições do seu sorriso!",
      "Você já se olhou no espelho e desejou um sorriso mais bonito, branco e saudável? A dentística une estética e saúde bucal para transformar o seu sorriso, corrigindo imperfeições..",
      "Quero melhorar meu sorriso",
      "Chegou sua hora de ter dentes perfeitos: elimine manchas, fraturas e imperfeições do seu sorriso!",
      "O que é dentística?",
      "A dentística é uma área da odontologia que cuida da estética e da funcionalidade dos dentes. Com técnicas modernas e materiais de alta qualidade, o Dr. Edi pode corrigir manchas, fraturas, desgastes e até mesmo melhorar o formato e o alinhamento do seu sorriso.",
      "Estes são os principais tratamentos de dentística:",
      "Restaurações estéticas",
      "Devolvem a função e a beleza dos dentes com materiais da cor natural.",
      "Clareamento dentário",
      "Dentes mais brancos e radiantes com segurança.",
      "Fechamento de diastemas",
      "Elimina os espaços indesejados entre os dentes.",
      "Facetas de resina ou porcelana",
      "Transformam o sorriso, corrigindo cor, formato e alinhamento.",
      "Por que escolher o Dr. Edi e sua equipe?",
      "Com procedimentos rápidos, minimamente invasivos e utilizando técnicas modernas, o Dr. Edi e sua equipe garantem resultados naturais e duradouros, sempre priorizando seu conforto e bem-estar.",
      "Profissionais experientes e qualificados",
      "Materiais de alta qualidade para resultados naturais",
      "Técnicas modernas e minimamente invasivas",
      "Atendimento humanizado e sem pressa",
      "Profissional experiente e qualificado",
      "Para quem a dentística é indicada?",
      "Para quem deseja corrigir manchas e amarelados nos dentes",
      "Para quem tem pequenas fraturas ou desgastes nos dentes",
      "Para quem busca melhorar o formato e o alinhamento do sorriso",
      "Para quem deseja fechar pequenos espaços entre os dentes (diastemas)",
      "Para quem quer transformar o sorriso de forma rápida e eficaz",
      "Sorrisos transformados que passaram por nossas mãos",
      "Nossos pacientes já passaram por essa jornada e hoje são prova de que é possível ter um sorriso bonito e funcional novamente.",
      "Confira os Depoimentos:",
      "A satisfação dos nossos pacientes é nossa motivação.",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Garanta seu novo sorriso agora!",
      "Chegou a hora de ter o sorriso bonito e saudável que você sempre sonhou. Agende sua avaliação com o Dr. Edi e descubra como a dentística pode transformar a sua vida!",
      "Perguntas Frequentes",
      "Os tratamentos de dentística são dolorosos?",
      "Não! A maioria dos procedimentos são minimamente invasivos e, quando necessário, utilizamos anestesia local para garantir seu conforto.",
      "O resultado é natural?",
      "Sim! Utilizamos materiais de alta qualidade e técnicas modernas para garantir um sorriso bonito e natural.",
      "Quanto tempo dura o resultado?",
      "Com os cuidados adequados, os resultados podem durar muitos anos! O Dr. Edi oferece orientações para manter seu sorriso sempre lindo.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/02/1-1-300x300.webp",
      "/site-assets/2025/02/2-1-300x300.webp",
      "/site-assets/2025/02/3-1-300x300.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Dentistica-1-300x300.webp",
      "/site-assets/2025/03/Dentistica-3-300x300.webp",
      "/site-assets/2025/03/Dentistica-4-300x300.webp",
      "/site-assets/2025/03/Dentistica-5-1024x1024.webp",
      "/site-assets/2025/03/Dentistica-5-150x150.webp",
      "/site-assets/2025/03/Dentistica-5-300x300.webp",
      "/site-assets/2025/03/Dentistica-5-768x768.webp",
      "/site-assets/2025/03/Dentistica-5.webp",
      "/site-assets/2025/03/Design-sem-nome-12-1024x1024.webp",
      "/site-assets/2025/03/Design-sem-nome-12-150x150.webp",
      "/site-assets/2025/03/Design-sem-nome-12-300x300.webp",
      "/site-assets/2025/03/Design-sem-nome-12-768x768.webp",
      "/site-assets/2025/03/Design-sem-nome-12.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/03/Porcelana-1024x1024.webp",
      "/site-assets/2025/03/Porcelana-150x150.webp",
      "/site-assets/2025/03/Porcelana-300x300.webp",
      "/site-assets/2025/03/Porcelana-768x768.webp",
      "/site-assets/2025/03/Porcelana.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2025/03/Resina-1024x1024.webp",
      "/site-assets/2025/03/Resina-150x150.webp",
      "/site-assets/2025/03/Resina-300x300.webp",
      "/site-assets/2025/03/Resina-768x768.webp",
      "/site-assets/2025/03/Resina.webp",
      "/site-assets/2025/03/Restauracao-300x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 1425,
    "slug": "endodontia",
    "title": "Endodontia",
    "link": "https://dredi.com.br/endodontia/",
    "headings": [
      "Não sofra mais com dor de dente: Trate o canal hoje mesmo!",
      "Não sofra mais com dor de dente: Trate o canal hoje mesmo!",
      "O que é endondontia?",
      "Como funciona o tratamento de canal?",
      "1. Diagnóstico preciso:",
      "2. Remoção da polpa infectada:",
      "3. Limpeza e desinfecção:",
      "4. Selamento do dente:",
      "Benefícios do tratamento:",
      "Para quem o tratamento de canal é indicada?",
      "Pessoas que sentem dor de dente intensa e persistente",
      "Quem tem sensibilidade ao quente e ao frio",
      "Pacientes que notam inchaço na gengiva ou abscessos",
      "Pessoas com cáries profundas que atingiram a raiz do dente",
      "Quem sofreu traumas dentários e precisa preservar o dente natural",
      "Pessoas que desejam evitar a extração do dente",
      "Mitos e verdades sobre o canal",
      "Veja o que dizem nossos pacientes sobre o tratamento de endodontia:",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Pare de sofrer com dor de dente agora mesmo!",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero dentes mais brancos",
      "Quero melhorar meu sorriso"
    ],
    "text": [
      "Não sofra mais com dor de dente: Trate o canal hoje mesmo!",
      "Diga adeus à dor, ao inchaço e ao desconforto. O tratamento de endodontia pode salvar seu dente e devolver sua qualidade de vida.",
      "Quero dentes mais brancos",
      "Quero melhorar meu sorriso",
      "O que é endondontia?",
      "A endodontia é a especialidade da odontologia que trata da parte interna do dente, conhecida como polpa dental. quando essa região é afetada por cáries profundas, traumas ou infecções, o tratamento de canal se torna essencial para remover o tecido danificado, desinfectar o local e preservar a estrutura do dente.",
      "Como funciona o tratamento de canal?",
      "1. Diagnóstico preciso:",
      "Utilizamos tecnologia avançada para avaliar o estado do seu dente.",
      "2. Remoção da polpa infectada:",
      "O dentista acessa a raiz do dente e remove o tecido comprometido.",
      "3. Limpeza e desinfecção:",
      "O canal é limpo e preparado para o preenchimento.",
      "4. Selamento do dente:",
      "O canal é preenchido com material adequado e o dente é restaurado.",
      "Benefícios do tratamento:",
      "Se você está sofrendo com dor de dente intensa, sensibilidade ao quente e ao frio, ou percebe inchaço na gengiva, pode ser um sinal de que precisa de um tratamento de canal. Essa é a solução ideal para eliminar a infecção, aliviar a dor e evitar a perda do dente.",
      "Alívio imediato da dor",
      "Preservação do dente natural",
      "Prevenção de infecções mais graves",
      "Restauração da saúde bucal",
      "Melhora na qualidade de vida",
      "Retorno da confiança ao comer e falar",
      "Fim da ansiedade causada pela dor",
      "Para quem o tratamento de canal é indicada?",
      "Pessoas que sentem dor de dente intensa e persistente",
      "Quem tem sensibilidade ao quente e ao frio",
      "Pacientes que notam inchaço na gengiva ou abscessos",
      "Pessoas com cáries profundas que atingiram a raiz do dente",
      "Quem sofreu traumas dentários e precisa preservar o dente natural",
      "Pessoas que desejam evitar a extração do dente",
      "Mitos e verdades sobre o canal",
      "O tratamento de canal dói?",
      "A maioria dos pacientes relata que o procedimento é indolor, graças à anestesia moderna e à técnica avançada.",
      "É melhor extrair o dente do que fazer o canal?",
      "Preservar o dente natural sempre é a melhor escolha. Mas em alternativa, o tratamento de canal evita a perda do dente e mantém a mastigação e a estética bucal.",
      "O dente tratado com canal fica frágil?",
      "Depois do tratamento, o dente é restaurado de forma segura e durável, garantindo resistência e funcionalidade.",
      "O tratamento de canal demora muitas sessões?",
      "Geralmente, o tratamento é concluído em uma ou duas sessões, dependendo da complexidade do caso.",
      "Preciso ter algum cuidado especial após o tratamento de canal?",
      "Sim, é importante manter a higiene bucal em dia e seguir as orientações do dentista para garantir a durabilidade do tratamento.",
      "Veja o que dizem nossos pacientes sobre o tratamento de endodontia:",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Pare de sofrer com dor de dente agora mesmo!",
      "Agende sua avaliação pelo whatsapp e descubra como o tratamento de endodontia pode devolver seu conforto e sua saúde bucal.",
      "Perguntas Frequentes",
      "Quanto tempo dura o tratamento de canal?",
      "Em geral, o tratamento é realizado em uma ou duas sessões, dependendo da complexidade do caso.",
      "O dente tratado com canal pode voltar a doer?",
      "Quando o tratamento é feito corretamente, o dente não deve voltar a doer. a manutenção da higiene bucal é fundamental para evitar novos problemas.",
      "O dente fica escuro após o canal?",
      "em alguns casos pode ocorrer escurecimento, mas existem soluções estéticas, como facetas e clareamentos, que resolvem essa questão.",
      "Quanto tempo dura o efeito do tratamento de canal?",
      "O tratamento é definitivo, mas a durabilidade do dente depende dos cuidados diários e da manutenção periódica com o dentista.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8-1.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 2296,
    "slug": "ortodontia",
    "title": "Ortodontia",
    "link": "https://dredi.com.br/ortodontia/",
    "headings": [
      "Seu novo sorriso começa aqui: Chegou a hora de transformar seu sorriso com um tratamento ortodôntico moderno e sob medida para você.",
      "Seu novo sorriso começa aqui: Chegou a hora de transformar seu sorriso com um tratamento ortodôntico moderno e sob medida para você.",
      "Você sabia que dentes desalinhados podem causar dores de cabeça, problemas de sono e dificuldades na mastigação?",
      "Por que fazer um tratamento ortodôntico?",
      "1. Melhora na saúde bucal",
      "2. Função mastigatória eficiente:",
      "3. Correção da fala e respiração:",
      "4. Autoestima elevada:",
      "Esse tratamento é para você que:",
      "Conheça os tipos de aparelhos que oferecemos:",
      "Aparelho fixo convencional",
      "Aparelho ortopédico",
      "Alinhadores invisíveis",
      "Veja o que dizem nossos pacientes sobre o tratamento de ortodontia:",
      "Confira alguns resultados de quem já fez o tratamento:",
      "Quem é o Dr. Edi...",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Corrija o desalinhamento dos seus dentes com segurança e eficiência!",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero saber mais detalhes"
    ],
    "text": [
      "Seu novo sorriso começa aqui: Chegou a hora de transformar seu sorriso com um tratamento ortodôntico moderno e sob medida para você.",
      "Tratamentos ortodônticos personalizados com tecnologia de ponta e foco em resultados reais.",
      "Quero saber mais detalhes",
      "Você sabia que dentes desalinhados podem causar dores de cabeça, problemas de sono e dificuldades na mastigação?",
      "A ortodontia vai muito além da estética. É saúde, é qualidade de vida, confiança e bem-estar. Aqui na clínica Vida Mais, oferecemos soluções ortodônticas modernas, seguras e eficientes, pensadas especialmente para o seu caso. Você não precisa escolher entre resultado e conforto: aqui, você tem os dois.",
      "Por que fazer um tratamento ortodôntico?",
      "1. Melhora na saúde bucal",
      "Dentes alinhados facilitam a higienização e reduzem o risco de cáries e problemas gengivais.",
      "2. Função mastigatória eficiente:",
      "Com os dentes na posição correta, a mastigação se torna mais eficaz e confortável.",
      "3. Correção da fala e respiração:",
      "Desalinhamentos podem afetar a fala e a respiração; o tratamento ajuda a restaurar essas funções.",
      "4. Autoestima elevada:",
      "Um sorriso harmônico e bem alinhado melhora a imagem pessoal e a confiança no dia a dia.",
      "Esse tratamento é para você que:",
      "Sente vergonha ao sorrir por causa dos dentes tortos",
      "Quer melhorar sua estética e mastigação",
      "Busca discrição e conforto com alinhadores modernos",
      "Procura um atendimento profissional e cuidadoso",
      "O tratamento ortodôntico vai muito além da aparência. Dentes desalinhados podem afetar a mastigação, a fala e até mesmo a saúde bucal, aumentando o risco de cáries e problemas na gengiva. Corrigir a posição dos dentes é investir em funcionalidade, saúde e autoestima.",
      "Conheça os tipos de aparelhos que oferecemos:",
      "Aparelho fixo convencional",
      "O clássico aparelho fixo que é altamente eficaz para casos mais complexos.",
      "Aparelho ortopédico",
      "Aparelhos móveis indicados principalmente para crianças e adolescentes em fase de crescimento.",
      "Alinhadores invisíveis",
      "Ideal para quem quer resultados sem abrir mão de discrição e conforto.",
      "Veja o que dizem nossos pacientes sobre o tratamento de ortodontia:",
      "Confira alguns resultados de quem já fez o tratamento:",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Corrija o desalinhamento dos seus dentes com segurança e eficiência!",
      "Agende sua avaliação pelo whatsapp e descubra qual tratamento ortodôntico é ideal para transformar o seu sorriso.",
      "Perguntas Frequentes",
      "Quanto tempo dura um tratamento ortodôntico?",
      "O tempo varia conforme a complexidade do caso e o tipo de aparelho utilizado. Em média, os tratamentos duram entre 12 e 30 meses.",
      "O tratamento com alinhadores é tão eficaz quanto o aparelho fixo?",
      "Sim, para casos leves a moderados, os alinhadores são altamente eficazes. Além disso, oferecem conforto, discrição e facilidade na higiene bucal.",
      "Dói usar aparelho ortodôntico?",
      "É comum sentir um leve desconforto nos primeiros dias após a ativação ou troca dos alinhadores, mas isso é temporário e indica que os dentes estão se movimentando como esperado.",
      "Posso escolher o tipo de aparelho que quero usar?",
      "Sim, após a avaliação, o profissional irá indicar as opções mais adequadas para o seu caso. juntos, vocês podem decidir o melhor caminho, considerando estética, custo e resultado desejado.",
      "Aceitam convêncio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8-1.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/09/Dr-Edi.webp",
      "/site-assets/2025/05/Ortodontia-1024x1024.webp",
      "/site-assets/2025/05/Ortodontia-150x150.webp",
      "/site-assets/2025/05/Ortodontia-2-1-1024x1024.webp",
      "/site-assets/2025/05/Ortodontia-2-1-150x150.webp",
      "/site-assets/2025/05/Ortodontia-2-1-300x300.webp",
      "/site-assets/2025/05/Ortodontia-2-1-768x768.webp",
      "/site-assets/2025/05/Ortodontia-2-1.webp",
      "/site-assets/2025/05/Ortodontia-3-1-1024x1024.webp",
      "/site-assets/2025/05/Ortodontia-3-1-150x150.webp",
      "/site-assets/2025/05/Ortodontia-3-1-300x300.webp",
      "/site-assets/2025/05/Ortodontia-3-1-768x768.webp",
      "/site-assets/2025/05/Ortodontia-3-1.webp",
      "/site-assets/2025/05/Ortodontia-300x300.webp",
      "/site-assets/2025/05/Ortodontia-768x768.webp",
      "/site-assets/2025/05/Ortodontia.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-1024x1024.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-150x150.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-2-1024x1024.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-2-150x150.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-2-300x300.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-2-768x768.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-2.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-3-1024x1024.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-3-150x150.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-3-300x300.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-3-768x768.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-3.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-300x300.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos-768x768.webp",
      "/site-assets/2025/05/Tratamentos-ortodonticos.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 2482,
    "slug": "home",
    "title": "Home",
    "link": "https://dredi.com.br/",
    "headings": [
      "Confiança, experiência e cuidado em cada sorriso com o Dr. Edi.",
      "Temos a solução ideal para você!",
      "Dentística",
      "Clareamento",
      "Próteses",
      "Implantes dentários",
      "Facetas e coroas",
      "Histórias reais de transformação",
      "Confira os Depoimentos:",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Não deixe que a falta de um sorriso completo limite sua vida.",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Agendar agora"
    ],
    "text": [
      "Confiança, experiência e cuidado em cada sorriso com o Dr. Edi.",
      "Nossa clínica oferece tratamentos completos para deixar seu sorriso mais bonito, saudável e funcional.",
      "Agendar agora",
      "Seja para recuperar um dente perdido, melhorar a estética ou cuidar da sua saúde bucal…",
      "Temos a solução ideal para você!",
      "Dentística",
      "Cuidados estéticos e funcionais para sua saúde bucal.",
      "Clareamento",
      "Dentes mais brancos e radiantes com segurança.",
      "Próteses",
      "Restaure a função e a estética do seu sorriso.",
      "Implantes dentários",
      "A solução definitiva para substituir dentes perdidos.",
      "Facetas e coroas",
      "Transformação estética para um sorriso impecável.",
      "Escolha o tratamento ideal para você e agende uma avaliação!",
      "Histórias reais de transformação",
      "Nossos pacientes já passaram por essa jornada e hoje são prova de que é possível ter um sorriso bonito e funcional novamente.",
      "Confira os Depoimentos:",
      "A satisfação dos nossos pacientes é nossa motivação.",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Não deixe que a falta de um sorriso completo limite sua vida.",
      "Agende uma avaliação e descubra a melhor solução para você.",
      "Perguntas Frequentes",
      "Como funciona a avaliação odontológica?",
      "Na avaliação, realizamos uma análise completa da sua saúde bucal. Utilizamos equipamentos modernos, como a câmera intra-oral para identificar possíveis problemas e definir o melhor plano de tratamento para você. Tudo de forma clara e personalizada.",
      "Vocês aceitam convênios odontológicos?",
      "Não trabalhamos com convênios, mas oferecemos condições especiais de pagamento para tornar seu tratamento mais acessível.",
      "O que é a câmera intra-oral?",
      "É um equipamento moderno que permite visualizar em alta definição todas as áreas da boca. Durante a avaliação, mostramos essas imagens para que você entenda exatamente a sua situação bucal e possa acompanhar todo o diagnóstico.",
      "Quanto tempo dura a avaliação?",
      "A avaliação dura, em média, de 30 a 45 minutos, dependendo da complexidade do caso. é um momento para entender suas necessidades e esclarecer todas as suas dúvidas.",
      "Como agendar uma avaliação??",
      "Você pode agendar sua avaliação de forma rápida e prática pelo whatsapp ou ligando para nossa clínica. teremos prazer em atender você.",
      "Atendem casos de emergência?",
      "Sim, atendemos emergências odontológicas. se você estiver com dor, inchaço ou sofreu algum trauma dental, entre em contato para encaixarmos seu atendimento o quanto antes.",
      "Como saber qual tratamento é o ideal para mim?",
      "Durante a avaliação, analisamos seu caso de forma individualizada e explicamos as opções de tratamento mais adequadas para seu objetivo, sempre respeitando suas necessidades e expectativas."
    ],
    "images": [
      "/site-assets/2025/01/1-300x300.webp",
      "/site-assets/2025/01/4-300x300.webp",
      "/site-assets/2025/01/5-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-1-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-2-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-3-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-4-300x300.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Clareamento-1-300x300.webp",
      "/site-assets/2025/03/Clareamento-1024x1024.webp",
      "/site-assets/2025/03/Clareamento-150x150.webp",
      "/site-assets/2025/03/Clareamento-300x300.webp",
      "/site-assets/2025/03/Clareamento-768x768.webp",
      "/site-assets/2025/03/Clareamento.webp",
      "/site-assets/2025/03/Facetas-4-300x300.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8-1.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/03/Porcelana-1-300x300.webp",
      "/site-assets/2025/03/Resina-1-300x300.webp",
      "/site-assets/2025/03/Restauracao-300x300.webp",
      "/site-assets/2025/09/4-1-150x150.webp",
      "/site-assets/2025/09/4-1-300x300.webp",
      "/site-assets/2025/09/4-1-768x768.webp",
      "/site-assets/2025/09/4-1.webp",
      "/site-assets/2025/09/5-1-300x300.webp",
      "/site-assets/2025/09/6-150x150.webp",
      "/site-assets/2025/09/6-300x300.webp",
      "/site-assets/2025/09/6-768x768.webp",
      "/site-assets/2025/09/6.webp",
      "/site-assets/2025/09/7-150x150.webp",
      "/site-assets/2025/09/7-300x300.webp",
      "/site-assets/2025/09/7-768x768.webp",
      "/site-assets/2025/09/7.webp",
      "/site-assets/2025/09/Dr-Edi-150x150.webp",
      "/site-assets/2025/09/Dr-Edi-300x300.webp",
      "/site-assets/2025/09/Dr-Edi-768x768.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2025/09/Dr-Edi.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 2532,
    "slug": "implantes",
    "title": "Implantes",
    "link": "https://dredi.com.br/implantes/",
    "headings": [
      "Redescubra sua melhor versão e recupere seu sorriso com implantes dentários de alta tecnologia!",
      "Você sente algum destes sintomas?",
      "Dores na boca ou dentes",
      "Dificuldade ao mastigar",
      "Vergonha ao sorrir",
      "Má aparência facial",
      "Desconforto",
      "Fala prejudicada",
      "Você não precisa conviver com isso para sempre!",
      "Quem é o Dr. Edi...",
      "Como posso transformar o seu sorriso?",
      "Confiança ao sorrir",
      "Redescubra o prazer e a confiança de sorrir com segurança e naturalidade, sem preocupações.",
      "Qualidade de vida",
      "Aproveite os momentos da vida com mais conforto e funcionalidade ao se alimentar e falar.",
      "Melhorar sua autoestima",
      "Sinta-se mais bonito(a) e confiante em qualquer situação.",
      "Tranquilidade ao falar",
      "Recupere a eficiência na mastigação e a tranquilidade ao interagir com as pessoas.",
      "Exclusividade",
      "Receba um tratamento exclusivo e planejado para atender às suas necessidades específicas.",
      "Quais tipos de implantes fazemos?",
      "Como funciona o tratamento?",
      "1. Primeiro passo:",
      "2. Segundo passo:",
      "3. Terceiro passo:",
      "4. Terceiro passo:",
      "Depoimentos de quem já está com um novo sorriso:",
      "Agora confira alguns dos resultados de nossos pacientes:",
      "Conheça a clínica vida mais!",
      "Dê o primeiro passo para cuidar de você.",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero recuperar meu sorriso"
    ],
    "text": [
      "Redescubra sua melhor versão e recupere seu sorriso com implantes dentários de alta tecnologia!",
      "A melhor solução para a falta de dentes com procedimentos modernos, rápidos e seguros. Recupere sua autoestima e confiança!",
      "Quero recuperar meu sorriso",
      "Você sente algum destes sintomas?",
      "Saiba que estes problemas têm solução!",
      "Dores na boca ou dentes",
      "Sensação de dor ou incômodo ao mastigar ou mesmo ao falar? Isso pode estar impedindo você de aproveitar suas refeições e seu dia a dia.",
      "Dificuldade ao mastigar",
      "Sente que sua mastigação não é mais a mesma e tem evitado certos alimentos? Isso pode ser um sinal de que você precisa de um implante dentário.",
      "Vergonha ao sorrir",
      "Você evita sorrir por causa de falhas ou espaços entre os dentes? Esse sentimento pode estar afetando sua autoestima e confiança.",
      "Má aparência facial",
      "Percebe que o formato do seu rosto está mudando por conta da perda dentária? Isso pode impactar sua autoestima e sua saúde bucal.",
      "Desconforto",
      "Se as próteses removíveis causam irritação ou não se ajustam bem, os implantes dentários podem ser a solução ideal para você.",
      "Fala prejudicada",
      "Dificuldade em pronunciar palavras corretamente por falta de dentes? Isso pode interferir na sua comunicação e autoconfiança.",
      "Você não precisa conviver com isso para sempre!",
      "A falta de um sorriso completo pode impactar diretamente sua qualidade de vida e autoestima. Algumas situações exigem a orientação de um profissional experiente e dedicado. Por isso, deixe-me apresentar…",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Como posso transformar o seu sorriso?",
      "Entre diferentes necessidades, estou aqui para cuidar de você e te ajudar a:",
      "Confiança ao sorrir",
      "Redescubra o prazer e a confiança de sorrir com segurança e naturalidade, sem preocupações.",
      "Qualidade de vida",
      "Aproveite os momentos da vida com mais conforto e funcionalidade ao se alimentar e falar.",
      "Melhorar sua autoestima",
      "Sinta-se mais bonito(a) e confiante em qualquer situação.",
      "Tranquilidade ao falar",
      "Recupere a eficiência na mastigação e a tranquilidade ao interagir com as pessoas.",
      "Exclusividade",
      "Receba um tratamento exclusivo e planejado para atender às suas necessidades específicas.",
      "Quais tipos de implantes fazemos?",
      "Implantes unitário: Perfeito para substituir um único dente.",
      "Implante carga imediata: Utilizada para prótese protocolo que é fixa sobre implantes, que é ideal para arcadas completas. Superior ou inferior ou ambas.",
      "Implante múltiplo: Para reposição de 3 ou mais dentes.",
      "Como funciona o tratamento?",
      "É simples, prático e feito para você...",
      "1. Primeiro passo:",
      "Avaliação inicial: Exame clínico, radiografia e tomografia.",
      "2. Segundo passo:",
      "Cirurgia de Implante: Instalação do implante dentário.",
      "3. Terceiro passo:",
      "Prótese Temporária: Colocação da prótese provisória, que será substituída após o tempo determinado.",
      "4. Terceiro passo:",
      "Acompanhamento: Monitoramento para garantir resultados duradouros.",
      "Depoimentos de quem já está com um novo sorriso:",
      "Agora confira alguns dos resultados de nossos pacientes:",
      "Você merece ser (o) a próximo(a)!",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Dê o primeiro passo para cuidar de você.",
      "Ter um sorriso bonito não é luxo. É investimento na sua saúde. Você merece!",
      "Perguntas Frequentes",
      "O que é implante de carga imediata?",
      "Uma técnica que permite a colocação de prótese logo após a cirurgia.",
      "Quanto tempo dura um implante?",
      "Com os cuidados adequados, pode durar a vida toda.",
      "O tratamento é doloroso?",
      "Com a anestesia local e as técnicas modernas, o desconforto é mínimo.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2025/01/1-300x300.webp",
      "/site-assets/2025/01/2-300x300.webp",
      "/site-assets/2025/01/3-300x300.webp",
      "/site-assets/2025/01/4-300x300.webp",
      "/site-assets/2025/01/5-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-1-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-2-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-3-300x300.webp",
      "/site-assets/2025/01/Implantes-resultados-4-300x300.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp"
    ]
  },
  {
    "id": 2552,
    "slug": "facetas-e-coroas",
    "title": "Facetas e Coroas",
    "link": "https://dredi.com.br/facetas-e-coroas/",
    "headings": [
      "Transforme Seu Sorriso com Facetas em Resina ou Porcelana!",
      "Por que escolher nossas facetas dentárias?",
      "Aparência natural",
      "Correção estética",
      "Durabilidade e Resistência",
      "Minimamente invasivo",
      "Lentes de contato dentais: O Avanço da estética bucal",
      "Facetas dentárias em resina composta",
      "Facetas dentárias em porcelana",
      "Coroas E-max: O melhor da estética dentária",
      "Por que escolher nossas facetas dentárias?",
      "Aparência natural",
      "Correção estética",
      "Durabilidade e Resistência",
      "Minimamente invasivo",
      "Lentes de contato dentais: O avanço da estética bucal",
      "Facetas dentárias em resina composta",
      "Facetas dentárias em porcelana",
      "Coroas E-max: O melhor da estética dentária",
      "Sorrisos transformados que passaram por nossas mãos",
      "Confira os Depoimentos:",
      "Como funciona o tratamento?",
      "Consulta Inicial",
      "Preparação dos Dentes",
      "Aplicação das Facetas",
      "Ajustes e Finalização",
      "Quem é o Dr. Edi...",
      "Conheça a clínica vida mais!",
      "Pronto para transformar seu sorriso?",
      "Perguntas Frequentes"
    ],
    "buttons": [
      "Quero ter um sorriso mais bonito"
    ],
    "text": [
      "Transforme Seu Sorriso com Facetas em Resina ou Porcelana!",
      "Sorria com confiança! Descubra como podemos renovar sua estética dental.",
      "Quero ter um sorriso mais bonito",
      "Na clínica do Dr. Edi, oferecemos soluções estéticas de ponta com facetas dentárias em resina ou porcelana, ideais para quem busca um sorriso mais bonito e natural. Seja para corrigir imperfeições ou simplesmente melhorar a estética, nossas facetas são a escolha perfeita.",
      "Por que escolher nossas facetas dentárias?",
      "Aparência natural",
      "Nossas facetas em porcelana ou em resina são projetadas para camuflagem perfeita.",
      "Correção estética",
      "Soluções eficazes para trincas, manchas e irregularidades dentárias.",
      "Durabilidade e Resistência",
      "Materiais de alta qualidade que garantem um sorriso duradouro.",
      "Minimamente invasivo",
      "Técnica que preserva ao máximo a estrutura natural dos dentes.",
      "Lentes de contato dentais: O Avanço da estética bucal",
      "As lentes de contato dentais são a evolução na odontologia estética, permitindo uma transformação sutil e eficaz no sorriso.",
      "São ideais para corrigir pequenas imperfeições, como espaçamentos ou descoloração, sem comprometer a estrutura do dente.",
      "Facetas dentárias em resina composta",
      "Se você busca uma transformação rápida e acessível para o seu sorriso, as facetas de resina composta são uma excelente opção.",
      "Elas corrigem trincas, desgastes, manchas e pequenas irregularidades, proporcionando um resultado natural e harmonioso.",
      "Além disso, são aplicadas em um único dia, garantindo um sorriso renovado de forma ágil e eficiente.",
      "Procedimento rápido e minimamente invasivo",
      "Solução acessível para corrigir imperfeições",
      "Resultado estético natural e imediato",
      "Facetas dentárias em porcelana",
      "As facetas de porcelana são a escolha perfeita para quem deseja um sorriso impecável com durabilidade e resistência superiores.",
      "Com uma aparência altamente natural, essas lâminas finas corrigem imperfeições e proporcionam um brilho duradouro, sem alterar a estrutura dos dentes. Ideais para quem busca um sorriso perfeito com longa duração.",
      "Alta resistência e durabilidade",
      "Aparência natural com brilho e translucidez semelhantes aos dentes naturais",
      "Mantêm a cor e o brilho por muitos anos",
      "Coroas E-max: O melhor da estética dentária",
      "As coroas E-max são a escolha ideal para quem busca uma reabilitação dental com máxima estética e naturalidade.",
      "Livre de metais, essas coroas permitem uma perfeita passagem de luz, mimetizando a beleza dos dentes naturais, tanto em dentes anteriores quanto posteriores.",
      "Ausência de borda escura, comum em coroas com metal",
      "Máxima naturalidade e estética",
      "A Solução ideal para reconstrução de dentes ou para montagem de novos sorrisos",
      "Na clínica do Dr. Edi, oferecemos soluções estéticas de ponta com facetas dentárias em resina e porcelana, ideais para quem busca um sorriso mais bonito e natural. Seja para corrigir imperfeições ou simplesmente melhorar a estética, nossas facetas são a escolha perfeita.",
      "Nossas facetas em porcelana e resina são projetadas para camuflagem perfeita.",
      "Aparência natural e harmoniosa",
      "Correção rápida e eficaz de imperfeições",
      "Opções em resina para ajustes rápidos e porcelana para maior durabilidade",
      "Sorrisos transformados que passaram por nossas mãos",
      "Nossos pacientes já passaram por essa jornada e hoje são prova de que é possível ter um sorriso bonito e funcional novamente.",
      "Confira os Depoimentos:",
      "A satisfação dos nossos pacientes é nossa motivação.",
      "Como funciona o tratamento?",
      "Consulta Inicial",
      "Avaliação e planejamento personalizado.",
      "Preparação dos Dentes",
      "Preparação mínima para garantir a adesão das facetas.",
      "Aplicação das Facetas",
      "Colocação das facetas em resina ou porcelana.",
      "Ajustes e Finalização",
      "Ajuste final para garantir o encaixe perfeito e a máxima naturalidade.",
      "Quem é o Dr. Edi...",
      "O Dr. Edi é cirurgião-dentista especialista em próteses dentárias e pós-graduado em implantes com mais de 20 anos de experiência prática e mais de 10 mil implantes realizados.  Sua missão é devolver sorrisos e transformar vidas. Ao longo dos anos, Dr. Edi e sua equipe ajudaram inúmeras pessoas a resgatar não apenas a funcionalidade dos dentes, mas também a confiança e a alegria de sorrir novamente.",
      "Formado pela renomada Unicamp e com especialização pela UNESP, seu trabalho vai muito além da estética, afinal, um sorriso completo impacta diretamente na sua autoestima, saúde e qualidade de vida. Por isso, o Dr. Edi utiliza as técnicas mais modernas e seguras, sempre com foco em resultados duradouros e no seu bem-estar.",
      "Cada paciente é único, e recebe atendimento personalizado, humano e acolhedor. Temos um compromisso de cuidar de você com dedicação, respeito e excelência, garantindo que o seu sorriso seja motivo de orgulho e felicidade todos os dias.",
      "Além do Dr. Edi, a clínica conta com uma equipe altamente qualificada, garantindo um atendimento completo e multidisciplinar. Juntos, oferecem uma experiência única, integrando estética e saúde para realçar sua beleza e bem-estar com segurança, qualidade e excelência.",
      "@doutoredi",
      "Conheça a clínica vida mais!",
      "Um lugar onde você será bem atendido, por uma equipe treinada e qualificada!",
      "Endereço: Avenida Jorge Tibiriçá, 1613 -",
      "Jardim das Oliveiras 13044-125, Campinas SP.",
      "Telefone:",
      "(19) 3276-0525",
      "Pronto para transformar seu sorriso?",
      "Agende sua avaliação e descubra como nossas facetas em resina ou porcelana podem realçar sua beleza natural.",
      "Perguntas Frequentes",
      "As facetas danificam os dentes naturais?",
      "Não. As facetas são projetadas para preservar ao máximo a estrutura natural dos dentes.",
      "Quanto tempo duram as facetas de porcelana?",
      "Com os cuidados adequados, as facetas de porcelana podem durar de 10 a 15 anos ou mais.",
      "As facetas podem corrigir dentes tortos?",
      "Sim, as facetas podem ser usadas para corrigir ligeiras imperfeições no alinhamento dos dentes.",
      "Aceitam convênio?",
      "Atualmente, não atendemos por convênios. Optamos por um atendimento 100% particular para oferecer mais liberdade na escolha dos tratamentos, utilizar materiais de alta qualidade e dedicar o tempo necessário a cada paciente, sem limitações impostas por planos. Assim, garantimos um cuidado personalizado, ético e focado nos melhores resultados para a sua saúde bucal."
    ],
    "images": [
      "/site-assets/2026/03/Coroas-e-max-1-1024x1024-1.webp",
      "/site-assets/2025/02/2-1-300x300.webp",
      "/site-assets/2025/02/3-1-300x300.webp",
      "/site-assets/2025/03/14-1-1.webp",
      "/site-assets/2025/03/14-2.webp",
      "/site-assets/2025/03/4-1.webp",
      "/site-assets/2025/03/5-1.webp",
      "/site-assets/2025/03/6-2-1.webp",
      "/site-assets/2025/03/7-2-1.webp",
      "/site-assets/2025/03/Coroas-1-300x300.webp",
      "/site-assets/2025/03/Coroas-2-300x300.webp",
      "/site-assets/2025/03/Coroas-3-300x300.webp",
      "/site-assets/2026/03/Faceta-1-1024x1024-1.webp",
      "/site-assets/2025/03/Facetas-1-300x300.webp",
      "/site-assets/2025/03/Facetas-3-1-300x300.webp",
      "/site-assets/2025/03/Facetas-3-300x300.webp",
      "/site-assets/2025/03/Facetas-4-300x300.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-1.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-2.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-3.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-4.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-5.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-6.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-7.webp",
      "/site-assets/2025/03/Feedbacks-dr-Edi-8.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-1024x617.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-300x181.webp",
      "/site-assets/2025/03/Logo-vida-brnaca-768x463.webp",
      "/site-assets/2025/03/Logo-vida-brnaca.webp",
      "/site-assets/2025/04/Emax-1024x1024.webp",
      "/site-assets/2025/04/Emax-150x150.webp",
      "/site-assets/2025/04/Emax-300x300.webp",
      "/site-assets/2025/04/Emax-768x768.webp",
      "/site-assets/2025/04/Emax.webp",
      "/site-assets/2025/04/Porcelana-1-1024x1024.webp",
      "/site-assets/2025/04/Porcelana-1-150x150.webp",
      "/site-assets/2025/04/Porcelana-1-300x300.webp",
      "/site-assets/2025/04/Porcelana-1-768x768.webp",
      "/site-assets/2025/04/Porcelana-1.webp",
      "/site-assets/2025/09/Dr-Edi-foto-240x300.webp",
      "/site-assets/2025/09/Dr-Edi-foto-768x960.webp",
      "/site-assets/2025/09/Dr-Edi-foto-819x1024.webp",
      "/site-assets/2025/09/Dr-Edi-foto.webp",
      "/site-assets/2026/03/10.webp",
      "/site-assets/2026/03/12.webp",
      "/site-assets/2026/03/13.webp",
      "/site-assets/2026/03/14.webp",
      "/site-assets/2026/03/15.webp",
      "/site-assets/2026/03/16.webp",
      "/site-assets/2026/03/17.webp",
      "/site-assets/2026/03/18.webp",
      "/site-assets/2026/03/20.webp",
      "/site-assets/2026/03/23.webp",
      "/site-assets/2026/03/24.webp",
      "/site-assets/2026/03/25.webp",
      "/site-assets/2026/03/3.webp",
      "/site-assets/2026/03/4.webp",
      "/site-assets/2026/03/5.webp",
      "/site-assets/2026/03/7.webp",
      "/site-assets/2026/03/9.webp",
      "/site-assets/2026/03/Coroas-e-max-1-1024x1024-1-150x150.webp",
      "/site-assets/2026/03/Coroas-e-max-1-1024x1024-1-300x300.webp",
      "/site-assets/2026/03/Coroas-e-max-1-1024x1024-1-768x768.webp",
      "/site-assets/2026/03/Coroas-e-max-1-1024x1024-1.webp",
      "/site-assets/2026/03/Faceta-1-1024x1024-1-150x150.webp",
      "/site-assets/2026/03/Faceta-1-1024x1024-1-300x300.webp",
      "/site-assets/2026/03/Faceta-1-1024x1024-1-768x768.webp",
      "/site-assets/2026/03/Faceta-1-1024x1024-1.webp"
    ]
  }
] as const

export type DrediPage = (typeof drediPages)[number]

export const servicePages = drediPages.filter((page) => page.slug !== "home")

export function getPageBySlug(slug: string) {
  return drediPages.find((page) => page.slug === slug)
}
