export type ServiceGalleryImage = {
  src: string
  alt: string
  originalName: string
  originalBytes: number
  optimizedBytes: number
}

export type ServiceGallery = {
  folder: string
  slug: string
  title: string
  heading: string
  description: string
  serviceHref: string
  serviceLabel: string
  images: ServiceGalleryImage[]
}

export const serviceGalleries = [
  {
    folder: "Alinhador",
    slug: "alinhador",
    title: "Alinhador invisível",
    heading: "Resultados com alinhador invisível",
    description: "Fotos de casos relacionados a alinhadores e planejamento ortodôntico para melhorar alinhamento, mordida e estética do sorriso.",
    serviceHref: "/ortodontia",
    serviceLabel: "Ortodontia",
    images: [
      {
        src: "/site-assets/service-galleries/alinhador/alinhador-01.webp",
        alt: "Alinhador invisível - caso 1",
        originalName: "alinhador (2).png",
        originalBytes: 2910686,
        optimizedBytes: 40744,
      },
      {
        src: "/site-assets/service-galleries/alinhador/alinhador-02.webp",
        alt: "Alinhador invisível - caso 2",
        originalName: "alinhador (3).png",
        originalBytes: 2370772,
        optimizedBytes: 46518,
      },
      {
        src: "/site-assets/service-galleries/alinhador/alinhador-03.webp",
        alt: "Alinhador invisível - caso 3",
        originalName: "alinhador invisível.png",
        originalBytes: 3220754,
        optimizedBytes: 49874,
      },
      {
        src: "/site-assets/service-galleries/alinhador/alinhador-04.webp",
        alt: "Alinhador invisível - caso 4",
        originalName: "alinhador.png",
        originalBytes: 3351673,
        optimizedBytes: 57384,
      },
    ],
  },
  {
    folder: "Clareamento dental",
    slug: "clareamento-dental",
    title: "Clareamento dental",
    heading: "Resultados de clareamento dental",
    description: "Fotos de clareamento dental profissional com acompanhamento para melhorar a tonalidade dos dentes com segurança.",
    serviceHref: "/clareamento",
    serviceLabel: "Clareamento",
    images: [
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-01.webp",
        alt: "Clareamento dental - caso 1",
        originalName: "clareamento  (10).png",
        originalBytes: 2103410,
        optimizedBytes: 119478,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-02.webp",
        alt: "Clareamento dental - caso 2",
        originalName: "clareamento  (11).png",
        originalBytes: 1436523,
        optimizedBytes: 57184,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-03.webp",
        alt: "Clareamento dental - caso 3",
        originalName: "clareamento  (12).png",
        originalBytes: 1748877,
        optimizedBytes: 84376,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-04.webp",
        alt: "Clareamento dental - caso 4",
        originalName: "clareamento (2).png",
        originalBytes: 2188799,
        optimizedBytes: 33830,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-05.webp",
        alt: "Clareamento dental - caso 5",
        originalName: "clareamento (3).png",
        originalBytes: 2551457,
        optimizedBytes: 44644,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-06.webp",
        alt: "Clareamento dental - caso 6",
        originalName: "clareamento (4).png",
        originalBytes: 2613731,
        optimizedBytes: 40320,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-07.webp",
        alt: "Clareamento dental - caso 7",
        originalName: "clareamento (5).png",
        originalBytes: 2376877,
        optimizedBytes: 43198,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-08.webp",
        alt: "Clareamento dental - caso 8",
        originalName: "clareamento (6).png",
        originalBytes: 1782432,
        optimizedBytes: 33842,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-09.webp",
        alt: "Clareamento dental - caso 9",
        originalName: "clareamento (7).png",
        originalBytes: 2213775,
        optimizedBytes: 54602,
      },
      {
        src: "/site-assets/service-galleries/clareamento-dental/clareamento-dental-10.webp",
        alt: "Clareamento dental - caso 10",
        originalName: "clareamento.png",
        originalBytes: 2179995,
        optimizedBytes: 32144,
      },
    ],
  },
  {
    folder: "coroa sobre dente",
    slug: "coroa-sobre-dente",
    title: "Coroa sobre dente",
    heading: "Resultados com coroa sobre dente",
    description: "Fotos de coroas dentárias planejadas para recuperar estrutura, função e estética de dentes comprometidos.",
    serviceHref: "/facetas-e-coroas",
    serviceLabel: "Facetas e coroas",
    images: [
      {
        src: "/site-assets/service-galleries/coroa-sobre-dente/coroa-sobre-dente-01.webp",
        alt: "Coroa sobre dente - caso 1",
        originalName: "coroa porcelana (2).png",
        originalBytes: 2094941,
        optimizedBytes: 38746,
      },
      {
        src: "/site-assets/service-galleries/coroa-sobre-dente/coroa-sobre-dente-02.webp",
        alt: "Coroa sobre dente - caso 2",
        originalName: "coroa porcelana.png",
        originalBytes: 1694743,
        optimizedBytes: 31762,
      },
      {
        src: "/site-assets/service-galleries/coroa-sobre-dente/coroa-sobre-dente-03.webp",
        alt: "Coroa sobre dente - caso 3",
        originalName: "coroa sobre dente em porcelana pura.png",
        originalBytes: 2379717,
        optimizedBytes: 31802,
      },
    ],
  },
  {
    folder: "Coroa sobre implante",
    slug: "coroa-sobre-implante",
    title: "Coroa sobre implante",
    heading: "Resultados com coroa sobre implante",
    description: "Fotos de reabilitação com coroa sobre implante para substituir dentes ausentes com planejamento funcional e estético.",
    serviceHref: "/implantes",
    serviceLabel: "Implantes",
    images: [
      {
        src: "/site-assets/service-galleries/coroa-sobre-implante/coroa-sobre-implante-01.webp",
        alt: "Coroa sobre implante - caso 1",
        originalName: "coroa implante.png",
        originalBytes: 1389332,
        optimizedBytes: 24602,
      },
    ],
  },
  {
    folder: "Facetas em Porcelana",
    slug: "facetas-em-porcelana",
    title: "Facetas em porcelana",
    heading: "Resultados com facetas em porcelana",
    description: "Fotos de facetas em porcelana para transformar formato, cor e harmonia do sorriso com naturalidade.",
    serviceHref: "/facetas-e-coroas",
    serviceLabel: "Facetas e coroas",
    images: [
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-01.webp",
        alt: "Facetas em porcelana - caso 1",
        originalName: "facetas em porcelana (2).png",
        originalBytes: 2297182,
        optimizedBytes: 40936,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-02.webp",
        alt: "Facetas em porcelana - caso 2",
        originalName: "facetas em porcelana (3).png",
        originalBytes: 2625885,
        optimizedBytes: 46574,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-03.webp",
        alt: "Facetas em porcelana - caso 3",
        originalName: "facetas em porcelana.png",
        originalBytes: 2225506,
        optimizedBytes: 39156,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-04.webp",
        alt: "Facetas em porcelana - caso 4",
        originalName: "porcela.png",
        originalBytes: 1777240,
        optimizedBytes: 35556,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-05.webp",
        alt: "Facetas em porcelana - caso 5",
        originalName: "porcelana (2).png",
        originalBytes: 2445057,
        optimizedBytes: 51348,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-06.webp",
        alt: "Facetas em porcelana - caso 6",
        originalName: "porcelana (3).png",
        originalBytes: 1610770,
        optimizedBytes: 29998,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-07.webp",
        alt: "Facetas em porcelana - caso 7",
        originalName: "porcelana (4).png",
        originalBytes: 2817285,
        optimizedBytes: 65708,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-08.webp",
        alt: "Facetas em porcelana - caso 8",
        originalName: "porcelana (5).png",
        originalBytes: 3093683,
        optimizedBytes: 94168,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-porcelana/facetas-em-porcelana-09.webp",
        alt: "Facetas em porcelana - caso 9",
        originalName: "porcelana (6).png",
        originalBytes: 1418718,
        optimizedBytes: 28498,
      },
    ],
  },
  {
    folder: "Facetas em Resina",
    slug: "facetas-em-resina",
    title: "Facetas em resina",
    heading: "Resultados com facetas em resina",
    description: "Fotos de estética em resina composta para melhorar formato, proporção e harmonia do sorriso.",
    serviceHref: "/facetas-e-coroas",
    serviceLabel: "Facetas e coroas",
    images: [
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-01.webp",
        alt: "Facetas em resina - caso 1",
        originalName: "estetica em resina composta (2).png",
        originalBytes: 2673476,
        optimizedBytes: 53290,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-02.webp",
        alt: "Facetas em resina - caso 2",
        originalName: "estetica em resina composta (3).png",
        originalBytes: 2531226,
        optimizedBytes: 50798,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-03.webp",
        alt: "Facetas em resina - caso 3",
        originalName: "estetica em resina composta (4).png",
        originalBytes: 2721198,
        optimizedBytes: 61872,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-04.webp",
        alt: "Facetas em resina - caso 4",
        originalName: "estetica em resina composta (5).png",
        originalBytes: 2078467,
        optimizedBytes: 36788,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-05.webp",
        alt: "Facetas em resina - caso 5",
        originalName: "estetica em resina composta (6).png",
        originalBytes: 2658464,
        optimizedBytes: 51650,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-06.webp",
        alt: "Facetas em resina - caso 6",
        originalName: "estetica em resina composta (7).png",
        originalBytes: 2382203,
        optimizedBytes: 39432,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-07.webp",
        alt: "Facetas em resina - caso 7",
        originalName: "estetica em resina composta (9).png",
        originalBytes: 2711309,
        optimizedBytes: 52308,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-08.webp",
        alt: "Facetas em resina - caso 8",
        originalName: "estetica em resina composta (11).png",
        originalBytes: 2059778,
        optimizedBytes: 47434,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-09.webp",
        alt: "Facetas em resina - caso 9",
        originalName: "estetica em resina composta.png",
        originalBytes: 2688258,
        optimizedBytes: 59904,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-10.webp",
        alt: "Facetas em resina - caso 10",
        originalName: "estetica em resina.png",
        originalBytes: 1679219,
        optimizedBytes: 33750,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-11.webp",
        alt: "Facetas em resina - caso 11",
        originalName: "resina  (4).png",
        originalBytes: 1091849,
        optimizedBytes: 32710,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-12.webp",
        alt: "Facetas em resina - caso 12",
        originalName: "resina  (6).png",
        originalBytes: 1607186,
        optimizedBytes: 49152,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-13.webp",
        alt: "Facetas em resina - caso 13",
        originalName: "resina  (7).png",
        originalBytes: 1487791,
        optimizedBytes: 47530,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-14.webp",
        alt: "Facetas em resina - caso 14",
        originalName: "resina  (8).png",
        originalBytes: 1104457,
        optimizedBytes: 33848,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-15.webp",
        alt: "Facetas em resina - caso 15",
        originalName: "resina  (17).png",
        originalBytes: 1487791,
        optimizedBytes: 47530,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-16.webp",
        alt: "Facetas em resina - caso 16",
        originalName: "resina  (18).png",
        originalBytes: 1091849,
        optimizedBytes: 32710,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-17.webp",
        alt: "Facetas em resina - caso 17",
        originalName: "resina  (19).png",
        originalBytes: 1050036,
        optimizedBytes: 33804,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-18.webp",
        alt: "Facetas em resina - caso 18",
        originalName: "resina  (20).png",
        originalBytes: 1107165,
        optimizedBytes: 32896,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-19.webp",
        alt: "Facetas em resina - caso 19",
        originalName: "resina  (21).png",
        originalBytes: 1104457,
        optimizedBytes: 33848,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-20.webp",
        alt: "Facetas em resina - caso 20",
        originalName: "resina  (22).png",
        originalBytes: 1607186,
        optimizedBytes: 49152,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-21.webp",
        alt: "Facetas em resina - caso 21",
        originalName: "resina  (23).png",
        originalBytes: 1487791,
        optimizedBytes: 47530,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-22.webp",
        alt: "Facetas em resina - caso 22",
        originalName: "resina  (30).png",
        originalBytes: 1036840,
        optimizedBytes: 29474,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-23.webp",
        alt: "Facetas em resina - caso 23",
        originalName: "resina  (32).png",
        originalBytes: 709991,
        optimizedBytes: 24350,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-24.webp",
        alt: "Facetas em resina - caso 24",
        originalName: "resina  (33).png",
        originalBytes: 1975849,
        optimizedBytes: 110822,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-25.webp",
        alt: "Facetas em resina - caso 25",
        originalName: "resina  (39).png",
        originalBytes: 1074072,
        optimizedBytes: 30862,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-26.webp",
        alt: "Facetas em resina - caso 26",
        originalName: "resina  (41).png",
        originalBytes: 1036840,
        optimizedBytes: 29474,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-27.webp",
        alt: "Facetas em resina - caso 27",
        originalName: "resina  (42).png",
        originalBytes: 1954782,
        optimizedBytes: 67388,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-28.webp",
        alt: "Facetas em resina - caso 28",
        originalName: "resina  (43).png",
        originalBytes: 1056612,
        optimizedBytes: 30212,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-29.webp",
        alt: "Facetas em resina - caso 29",
        originalName: "resina  (44).png",
        originalBytes: 1325687,
        optimizedBytes: 41070,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-30.webp",
        alt: "Facetas em resina - caso 30",
        originalName: "resina  (52).png",
        originalBytes: 1021654,
        optimizedBytes: 36194,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-31.webp",
        alt: "Facetas em resina - caso 31",
        originalName: "resina  (53).png",
        originalBytes: 968238,
        optimizedBytes: 29646,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-32.webp",
        alt: "Facetas em resina - caso 32",
        originalName: "resina  (54).png",
        originalBytes: 1123753,
        optimizedBytes: 34756,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-33.webp",
        alt: "Facetas em resina - caso 33",
        originalName: "resina  (55).png",
        originalBytes: 2027699,
        optimizedBytes: 28942,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-34.webp",
        alt: "Facetas em resina - caso 34",
        originalName: "resina  (56).png",
        originalBytes: 1691455,
        optimizedBytes: 66916,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-35.webp",
        alt: "Facetas em resina - caso 35",
        originalName: "resina  (57).png",
        originalBytes: 789168,
        optimizedBytes: 25716,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-36.webp",
        alt: "Facetas em resina - caso 36",
        originalName: "resina  (58).png",
        originalBytes: 1185234,
        optimizedBytes: 41070,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-37.webp",
        alt: "Facetas em resina - caso 37",
        originalName: "resina  (59).png",
        originalBytes: 942432,
        optimizedBytes: 30862,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-38.webp",
        alt: "Facetas em resina - caso 38",
        originalName: "resina  (60).png",
        originalBytes: 874663,
        optimizedBytes: 28214,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-39.webp",
        alt: "Facetas em resina - caso 39",
        originalName: "resina  (74).png",
        originalBytes: 806718,
        optimizedBytes: 27690,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-40.webp",
        alt: "Facetas em resina - caso 40",
        originalName: "resina  (75).png",
        originalBytes: 882825,
        optimizedBytes: 35426,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-41.webp",
        alt: "Facetas em resina - caso 41",
        originalName: "resina  (76).png",
        originalBytes: 878847,
        optimizedBytes: 27834,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-42.webp",
        alt: "Facetas em resina - caso 42",
        originalName: "resina  (77).png",
        originalBytes: 886613,
        optimizedBytes: 29140,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-43.webp",
        alt: "Facetas em resina - caso 43",
        originalName: "resina  (78).png",
        originalBytes: 855008,
        optimizedBytes: 26830,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-44.webp",
        alt: "Facetas em resina - caso 44",
        originalName: "resina  (79).png",
        originalBytes: 710444,
        optimizedBytes: 23310,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-45.webp",
        alt: "Facetas em resina - caso 45",
        originalName: "resina  (80).png",
        originalBytes: 1138195,
        optimizedBytes: 43342,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-46.webp",
        alt: "Facetas em resina - caso 46",
        originalName: "resina  (81).png",
        originalBytes: 2289041,
        optimizedBytes: 119572,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-47.webp",
        alt: "Facetas em resina - caso 47",
        originalName: "resina  (89).png",
        originalBytes: 846598,
        optimizedBytes: 30200,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-48.webp",
        alt: "Facetas em resina - caso 48",
        originalName: "resina  (90).png",
        originalBytes: 883261,
        optimizedBytes: 35400,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-49.webp",
        alt: "Facetas em resina - caso 49",
        originalName: "resina  (91).png",
        originalBytes: 879084,
        optimizedBytes: 27834,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-50.webp",
        alt: "Facetas em resina - caso 50",
        originalName: "Resina (1).png",
        originalBytes: 1618357,
        optimizedBytes: 70486,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-51.webp",
        alt: "Facetas em resina - caso 51",
        originalName: "Resina (2).png",
        originalBytes: 1185575,
        optimizedBytes: 40426,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-52.webp",
        alt: "Facetas em resina - caso 52",
        originalName: "resina (2)(1).png",
        originalBytes: 2685268,
        optimizedBytes: 50724,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-53.webp",
        alt: "Facetas em resina - caso 53",
        originalName: "resina (3).png",
        originalBytes: 1935549,
        optimizedBytes: 37000,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-54.webp",
        alt: "Facetas em resina - caso 54",
        originalName: "resina (4).png",
        originalBytes: 2365368,
        optimizedBytes: 42976,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-55.webp",
        alt: "Facetas em resina - caso 55",
        originalName: "resina (5).png",
        originalBytes: 1527243,
        optimizedBytes: 27268,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-56.webp",
        alt: "Facetas em resina - caso 56",
        originalName: "Resina (6).png",
        originalBytes: 1185575,
        optimizedBytes: 40426,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-57.webp",
        alt: "Facetas em resina - caso 57",
        originalName: "resina (6)(1).png",
        originalBytes: 2247423,
        optimizedBytes: 45242,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-58.webp",
        alt: "Facetas em resina - caso 58",
        originalName: "Resina (7).png",
        originalBytes: 1618357,
        optimizedBytes: 70486,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-59.webp",
        alt: "Facetas em resina - caso 59",
        originalName: "resina (7)(1).png",
        originalBytes: 2575996,
        optimizedBytes: 53862,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-60.webp",
        alt: "Facetas em resina - caso 60",
        originalName: "resina (9).png",
        originalBytes: 1893434,
        optimizedBytes: 35842,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-61.webp",
        alt: "Facetas em resina - caso 61",
        originalName: "resina (10).png",
        originalBytes: 2316595,
        optimizedBytes: 48428,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-62.webp",
        alt: "Facetas em resina - caso 62",
        originalName: "resina (11).png",
        originalBytes: 2331800,
        optimizedBytes: 56454,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-63.webp",
        alt: "Facetas em resina - caso 63",
        originalName: "resina (12).png",
        originalBytes: 1613129,
        optimizedBytes: 27388,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-64.webp",
        alt: "Facetas em resina - caso 64",
        originalName: "resina (13).png",
        originalBytes: 2087240,
        optimizedBytes: 38986,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-65.webp",
        alt: "Facetas em resina - caso 65",
        originalName: "resina (17).png",
        originalBytes: 1867190,
        optimizedBytes: 31920,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-66.webp",
        alt: "Facetas em resina - caso 66",
        originalName: "resina (18).png",
        originalBytes: 2377068,
        optimizedBytes: 44124,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-67.webp",
        alt: "Facetas em resina - caso 67",
        originalName: "resina (19).png",
        originalBytes: 1504134,
        optimizedBytes: 28912,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-68.webp",
        alt: "Facetas em resina - caso 68",
        originalName: "resina (20).png",
        originalBytes: 2392633,
        optimizedBytes: 41812,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-69.webp",
        alt: "Facetas em resina - caso 69",
        originalName: "resina (21).png",
        originalBytes: 2127505,
        optimizedBytes: 46056,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-70.webp",
        alt: "Facetas em resina - caso 70",
        originalName: "resina (23).png",
        originalBytes: 2326966,
        optimizedBytes: 42948,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-71.webp",
        alt: "Facetas em resina - caso 71",
        originalName: "resina (24).png",
        originalBytes: 2536859,
        optimizedBytes: 56350,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-72.webp",
        alt: "Facetas em resina - caso 72",
        originalName: "resina (25).png",
        originalBytes: 2013222,
        optimizedBytes: 38932,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-73.webp",
        alt: "Facetas em resina - caso 73",
        originalName: "resina (26).png",
        originalBytes: 3180386,
        optimizedBytes: 87732,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-74.webp",
        alt: "Facetas em resina - caso 74",
        originalName: "resina p.png",
        originalBytes: 2033920,
        optimizedBytes: 39468,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-75.webp",
        alt: "Facetas em resina - caso 75",
        originalName: "Resina.png",
        originalBytes: 1018883,
        optimizedBytes: 43960,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-76.webp",
        alt: "Facetas em resina - caso 76",
        originalName: "resina(1).png",
        originalBytes: 1110728,
        optimizedBytes: 21486,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-77.webp",
        alt: "Facetas em resina - caso 77",
        originalName: "restauração  (98).png",
        originalBytes: 922963,
        optimizedBytes: 37004,
      },
      {
        src: "/site-assets/service-galleries/facetas-em-resina/facetas-em-resina-78.webp",
        alt: "Facetas em resina - caso 78",
        originalName: "WhatsApp Image 2025-08-11 at 16.56.13.jpeg",
        originalBytes: 176311,
        optimizedBytes: 37468,
      },
    ],
  },
  {
    folder: "Fechamento de diastema",
    slug: "fechamento-de-diastema",
    title: "Fechamento de diastema",
    heading: "Resultados de fechamento de diastema",
    description: "Fotos de fechamento de espaços entre dentes com planejamento estético e resina composta.",
    serviceHref: "/facetas-e-coroas",
    serviceLabel: "Facetas e coroas",
    images: [
      {
        src: "/site-assets/service-galleries/fechamento-de-diastema/fechamento-de-diastema-01.webp",
        alt: "Fechamento de diastema - caso 1",
        originalName: "fechamento de diastema (2).png",
        originalBytes: 2117450,
        optimizedBytes: 47482,
      },
      {
        src: "/site-assets/service-galleries/fechamento-de-diastema/fechamento-de-diastema-02.webp",
        alt: "Fechamento de diastema - caso 2",
        originalName: "fechamento de diastema com resina composta.png",
        originalBytes: 2124465,
        optimizedBytes: 47512,
      },
      {
        src: "/site-assets/service-galleries/fechamento-de-diastema/fechamento-de-diastema-03.webp",
        alt: "Fechamento de diastema - caso 3",
        originalName: "fechamento de diastema.png",
        originalBytes: 1718814,
        optimizedBytes: 36344,
      },
    ],
  },
  {
    folder: "Limpeza- tártaro",
    slug: "limpeza-tartaro",
    title: "Limpeza de tártaro",
    heading: "Resultados de limpeza de tártaro",
    description: "Fotos de limpeza odontológica para remover tártaro, melhorar saúde gengival e prevenir problemas bucais.",
    serviceHref: "/dentistica",
    serviceLabel: "Dentística",
    images: [
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-01.webp",
        alt: "Limpeza de tártaro - caso 1",
        originalName: "limpeza de tartaro (2).png",
        originalBytes: 2891995,
        optimizedBytes: 56536,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-02.webp",
        alt: "Limpeza de tártaro - caso 2",
        originalName: "limpeza de tartaro (3).png",
        originalBytes: 2115070,
        optimizedBytes: 48334,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-03.webp",
        alt: "Limpeza de tártaro - caso 3",
        originalName: "limpeza de tartaro.png",
        originalBytes: 2710035,
        optimizedBytes: 45000,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-04.webp",
        alt: "Limpeza de tártaro - caso 4",
        originalName: "tartaro  (1).png",
        originalBytes: 2105983,
        optimizedBytes: 71276,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-05.webp",
        alt: "Limpeza de tártaro - caso 5",
        originalName: "tartaro  (5).png",
        originalBytes: 2105983,
        optimizedBytes: 71276,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-06.webp",
        alt: "Limpeza de tártaro - caso 6",
        originalName: "tartaro  (6).png",
        originalBytes: 1832939,
        optimizedBytes: 53824,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-07.webp",
        alt: "Limpeza de tártaro - caso 7",
        originalName: "tartaro  (7).png",
        originalBytes: 1887109,
        optimizedBytes: 57568,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-08.webp",
        alt: "Limpeza de tártaro - caso 8",
        originalName: "tartaro  (8).png",
        originalBytes: 1803242,
        optimizedBytes: 57648,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-09.webp",
        alt: "Limpeza de tártaro - caso 9",
        originalName: "tartaro .png",
        originalBytes: 1887109,
        optimizedBytes: 57568,
      },
      {
        src: "/site-assets/service-galleries/limpeza-tartaro/limpeza-tartaro-10.webp",
        alt: "Limpeza de tártaro - caso 10",
        originalName: "tártaro.png",
        originalBytes: 2283762,
        optimizedBytes: 31632,
      },
    ],
  },
  {
    folder: "Piercing",
    slug: "piercing-dental",
    title: "Piercing dental",
    heading: "Fotos de piercing dental",
    description: "Fotos de piercing dental em contexto estético, com orientação profissional sobre cuidados e indicação.",
    serviceHref: "/dentistica",
    serviceLabel: "Dentística",
    images: [
      {
        src: "/site-assets/service-galleries/piercing-dental/piercing-dental-01.webp",
        alt: "Piercing dental - caso 1",
        originalName: "piercing.png",
        originalBytes: 2804597,
        optimizedBytes: 35734,
      },
    ],
  },
  {
    folder: "Prótese 5 elementos",
    slug: "protese-5-elementos",
    title: "Prótese 5 elementos",
    heading: "Resultados com prótese de 5 elementos",
    description: "Fotos de prótese dentária para reabilitação de múltiplos dentes com foco em função, estética e conforto.",
    serviceHref: "/proteses",
    serviceLabel: "Próteses",
    images: [
      {
        src: "/site-assets/service-galleries/protese-5-elementos/protese-5-elementos-01.webp",
        alt: "Prótese 5 elementos - caso 1",
        originalName: "prótese 5 elementos.png",
        originalBytes: 3077748,
        optimizedBytes: 101538,
      },
    ],
  },
  {
    folder: "Prótese protocolo",
    slug: "protese-protocolo",
    title: "Prótese protocolo",
    heading: "Resultados com prótese protocolo",
    description: "Fotos de prótese protocolo e reabilitação sobre implantes para recuperar mastigação e segurança ao sorrir.",
    serviceHref: "/proteses",
    serviceLabel: "Próteses",
    images: [
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-01.webp",
        alt: "Prótese protocolo - caso 1",
        originalName: "prótese  (1).png",
        originalBytes: 2622540,
        optimizedBytes: 144060,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-02.webp",
        alt: "Prótese protocolo - caso 2",
        originalName: "prótese móvel  (2).png",
        originalBytes: 855966,
        optimizedBytes: 33830,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-03.webp",
        alt: "Prótese protocolo - caso 3",
        originalName: "protese protocolo (2).png",
        originalBytes: 2085971,
        optimizedBytes: 33664,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-04.webp",
        alt: "Prótese protocolo - caso 4",
        originalName: "protese protocolo (3).png",
        originalBytes: 3067354,
        optimizedBytes: 60002,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-05.webp",
        alt: "Prótese protocolo - caso 5",
        originalName: "Prótese protocolo.png",
        originalBytes: 2618341,
        optimizedBytes: 45828,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-06.webp",
        alt: "Prótese protocolo - caso 6",
        originalName: "protese protocolo.png",
        originalBytes: 2005210,
        optimizedBytes: 32896,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-07.webp",
        alt: "Prótese protocolo - caso 7",
        originalName: "protese.png",
        originalBytes: 2799784,
        optimizedBytes: 53570,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-08.webp",
        alt: "Prótese protocolo - caso 8",
        originalName: "protocolo  (2).png",
        originalBytes: 2212169,
        optimizedBytes: 116768,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-09.webp",
        alt: "Prótese protocolo - caso 9",
        originalName: "protocolo  (3).png",
        originalBytes: 1346151,
        optimizedBytes: 27210,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-10.webp",
        alt: "Prótese protocolo - caso 10",
        originalName: "protocolo  (4).png",
        originalBytes: 1369008,
        optimizedBytes: 27268,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-11.webp",
        alt: "Prótese protocolo - caso 11",
        originalName: "protocolo  (5).png",
        originalBytes: 1347356,
        optimizedBytes: 25788,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-12.webp",
        alt: "Prótese protocolo - caso 12",
        originalName: "protocolo  (6).png",
        originalBytes: 2249664,
        optimizedBytes: 111200,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-13.webp",
        alt: "Prótese protocolo - caso 13",
        originalName: "protocolo  (9).png",
        originalBytes: 1581269,
        optimizedBytes: 39080,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-14.webp",
        alt: "Prótese protocolo - caso 14",
        originalName: "protocolo (2).png",
        originalBytes: 1819395,
        optimizedBytes: 35380,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-15.webp",
        alt: "Prótese protocolo - caso 15",
        originalName: "protocolo (3).png",
        originalBytes: 2249247,
        optimizedBytes: 40298,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-16.webp",
        alt: "Prótese protocolo - caso 16",
        originalName: "protocolo (4).png",
        originalBytes: 2214130,
        optimizedBytes: 49186,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-17.webp",
        alt: "Prótese protocolo - caso 17",
        originalName: "protocolo (5).png",
        originalBytes: 2539106,
        optimizedBytes: 51270,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-18.webp",
        alt: "Prótese protocolo - caso 18",
        originalName: "protocolo (6).png",
        originalBytes: 1672895,
        optimizedBytes: 26904,
      },
      {
        src: "/site-assets/service-galleries/protese-protocolo/protese-protocolo-19.webp",
        alt: "Prótese protocolo - caso 19",
        originalName: "protocolo (7).png",
        originalBytes: 1765085,
        optimizedBytes: 33338,
      },
    ],
  },
  {
    folder: "Restauração em resina",
    slug: "restauracao-em-resina",
    title: "Restauração em resina",
    heading: "Resultados de restauração em resina",
    description: "Fotos de restaurações em resina composta para recuperar dentes, corrigir desgaste e preservar naturalidade.",
    serviceHref: "/dentistica",
    serviceLabel: "Dentística",
    images: [
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-01.webp",
        alt: "Restauração em resina - caso 1",
        originalName: "resaturaçao  (1).png",
        originalBytes: 1028524,
        optimizedBytes: 29360,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-02.webp",
        alt: "Restauração em resina - caso 2",
        originalName: "resaturaçao .png",
        originalBytes: 1570043,
        optimizedBytes: 48248,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-03.webp",
        alt: "Restauração em resina - caso 3",
        originalName: "restauração  (1).png",
        originalBytes: 937006,
        optimizedBytes: 25546,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-04.webp",
        alt: "Restauração em resina - caso 4",
        originalName: "restauraçao  (4).png",
        originalBytes: 1570043,
        optimizedBytes: 48248,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-05.webp",
        alt: "Restauração em resina - caso 5",
        originalName: "restauraçao  (5).png",
        originalBytes: 1969411,
        optimizedBytes: 37150,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-06.webp",
        alt: "Restauração em resina - caso 6",
        originalName: "restauração  (5).png",
        originalBytes: 759477,
        optimizedBytes: 25964,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-07.webp",
        alt: "Restauração em resina - caso 7",
        originalName: "restauraçao  (6).png",
        originalBytes: 1303138,
        optimizedBytes: 33850,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-08.webp",
        alt: "Restauração em resina - caso 8",
        originalName: "restauração  (6).png",
        originalBytes: 1440891,
        optimizedBytes: 42408,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-09.webp",
        alt: "Restauração em resina - caso 9",
        originalName: "restauraçao  (7).png",
        originalBytes: 1028524,
        optimizedBytes: 29360,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-10.webp",
        alt: "Restauração em resina - caso 10",
        originalName: "restauração  (7).png",
        originalBytes: 1064748,
        optimizedBytes: 32904,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-11.webp",
        alt: "Restauração em resina - caso 11",
        originalName: "restauraçao  (8).png",
        originalBytes: 1356794,
        optimizedBytes: 30016,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-12.webp",
        alt: "Restauração em resina - caso 12",
        originalName: "restauração  (8).png",
        originalBytes: 937006,
        optimizedBytes: 25546,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-13.webp",
        alt: "Restauração em resina - caso 13",
        originalName: "restauração  (9).png",
        originalBytes: 1567427,
        optimizedBytes: 41484,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-14.webp",
        alt: "Restauração em resina - caso 14",
        originalName: "restauraçao  (10).png",
        originalBytes: 1973964,
        optimizedBytes: 36826,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-15.webp",
        alt: "Restauração em resina - caso 15",
        originalName: "restauração  (10).png",
        originalBytes: 1722977,
        optimizedBytes: 41028,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-16.webp",
        alt: "Restauração em resina - caso 16",
        originalName: "restauraçao  (11).png",
        originalBytes: 1033854,
        optimizedBytes: 29274,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-17.webp",
        alt: "Restauração em resina - caso 17",
        originalName: "restauração  (11).png",
        originalBytes: 1421953,
        optimizedBytes: 34982,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-18.webp",
        alt: "Restauração em resina - caso 18",
        originalName: "restauraçao  (12).png",
        originalBytes: 1973964,
        optimizedBytes: 36826,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-19.webp",
        alt: "Restauração em resina - caso 19",
        originalName: "restauração  (12).png",
        originalBytes: 1494348,
        optimizedBytes: 36876,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-20.webp",
        alt: "Restauração em resina - caso 20",
        originalName: "restauraçao  (13).png",
        originalBytes: 1973964,
        optimizedBytes: 36826,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-21.webp",
        alt: "Restauração em resina - caso 21",
        originalName: "restauração  (13).png",
        originalBytes: 2140667,
        optimizedBytes: 37800,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-22.webp",
        alt: "Restauração em resina - caso 22",
        originalName: "restauraçao  (14).png",
        originalBytes: 918407,
        optimizedBytes: 29274,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-23.webp",
        alt: "Restauração em resina - caso 23",
        originalName: "restauração  (15).png",
        originalBytes: 1632779,
        optimizedBytes: 40778,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-24.webp",
        alt: "Restauração em resina - caso 24",
        originalName: "restauração  (16).png",
        originalBytes: 1537229,
        optimizedBytes: 44766,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-25.webp",
        alt: "Restauração em resina - caso 25",
        originalName: "restauração  (21).png",
        originalBytes: 1643285,
        optimizedBytes: 44074,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-26.webp",
        alt: "Restauração em resina - caso 26",
        originalName: "restauração  (22).png",
        originalBytes: 1613430,
        optimizedBytes: 44320,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-27.webp",
        alt: "Restauração em resina - caso 27",
        originalName: "restauração  (23).png",
        originalBytes: 1450979,
        optimizedBytes: 42864,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-28.webp",
        alt: "Restauração em resina - caso 28",
        originalName: "restauração  (24).png",
        originalBytes: 1362966,
        optimizedBytes: 33714,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-29.webp",
        alt: "Restauração em resina - caso 29",
        originalName: "restauração  (25).png",
        originalBytes: 1145733,
        optimizedBytes: 30896,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-30.webp",
        alt: "Restauração em resina - caso 30",
        originalName: "restauração  (34).png",
        originalBytes: 1600641,
        optimizedBytes: 40482,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-31.webp",
        alt: "Restauração em resina - caso 31",
        originalName: "restauração  (35).png",
        originalBytes: 1473114,
        optimizedBytes: 39714,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-32.webp",
        alt: "Restauração em resina - caso 32",
        originalName: "restauração  (36).png",
        originalBytes: 1544486,
        optimizedBytes: 40726,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-33.webp",
        alt: "Restauração em resina - caso 33",
        originalName: "restauração  (37).png",
        originalBytes: 1514511,
        optimizedBytes: 42848,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-34.webp",
        alt: "Restauração em resina - caso 34",
        originalName: "restauração  (38).png",
        originalBytes: 1674624,
        optimizedBytes: 55130,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-35.webp",
        alt: "Restauração em resina - caso 35",
        originalName: "restauração  (39).png",
        originalBytes: 1663422,
        optimizedBytes: 47822,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-36.webp",
        alt: "Restauração em resina - caso 36",
        originalName: "restauração  (40).png",
        originalBytes: 1753380,
        optimizedBytes: 50172,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-37.webp",
        alt: "Restauração em resina - caso 37",
        originalName: "restauração  (41).png",
        originalBytes: 1679566,
        optimizedBytes: 45650,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-38.webp",
        alt: "Restauração em resina - caso 38",
        originalName: "restauração  (42).png",
        originalBytes: 1365039,
        optimizedBytes: 40160,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-39.webp",
        alt: "Restauração em resina - caso 39",
        originalName: "restauração  (43).png",
        originalBytes: 1643285,
        optimizedBytes: 44074,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-40.webp",
        alt: "Restauração em resina - caso 40",
        originalName: "restauração  (44).png",
        originalBytes: 1503839,
        optimizedBytes: 36810,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-41.webp",
        alt: "Restauração em resina - caso 41",
        originalName: "restauração  (45).png",
        originalBytes: 1426230,
        optimizedBytes: 34992,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-42.webp",
        alt: "Restauração em resina - caso 42",
        originalName: "restauração  (46).png",
        originalBytes: 1557488,
        optimizedBytes: 44518,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-43.webp",
        alt: "Restauração em resina - caso 43",
        originalName: "restauração  (47).png",
        originalBytes: 1641601,
        optimizedBytes: 40980,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-44.webp",
        alt: "Restauração em resina - caso 44",
        originalName: "restauração  (48).png",
        originalBytes: 2151765,
        optimizedBytes: 37584,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-45.webp",
        alt: "Restauração em resina - caso 45",
        originalName: "restauração  (49).png",
        originalBytes: 1613430,
        optimizedBytes: 44320,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-46.webp",
        alt: "Restauração em resina - caso 46",
        originalName: "restauração  (50).png",
        originalBytes: 1450979,
        optimizedBytes: 42864,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-47.webp",
        alt: "Restauração em resina - caso 47",
        originalName: "restauração  (51).png",
        originalBytes: 1145733,
        optimizedBytes: 30896,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-48.webp",
        alt: "Restauração em resina - caso 48",
        originalName: "restauração  (52).png",
        originalBytes: 1376128,
        optimizedBytes: 35348,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-49.webp",
        alt: "Restauração em resina - caso 49",
        originalName: "restauração  (53).png",
        originalBytes: 1629704,
        optimizedBytes: 42012,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-50.webp",
        alt: "Restauração em resina - caso 50",
        originalName: "restauração  (66).png",
        originalBytes: 1367317,
        optimizedBytes: 36810,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-51.webp",
        alt: "Restauração em resina - caso 51",
        originalName: "restauração  (67).png",
        originalBytes: 1284461,
        optimizedBytes: 34992,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-52.webp",
        alt: "Restauração em resina - caso 52",
        originalName: "restauração  (68).png",
        originalBytes: 1398706,
        optimizedBytes: 44518,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-53.webp",
        alt: "Restauração em resina - caso 53",
        originalName: "restauração  (69).png",
        originalBytes: 1432972,
        optimizedBytes: 40980,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-54.webp",
        alt: "Restauração em resina - caso 54",
        originalName: "restauração  (70).png",
        originalBytes: 2151765,
        optimizedBytes: 37584,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-55.webp",
        alt: "Restauração em resina - caso 55",
        originalName: "restauração  (71).png",
        originalBytes: 1436653,
        optimizedBytes: 44320,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-56.webp",
        alt: "Restauração em resina - caso 56",
        originalName: "restauração  (72).png",
        originalBytes: 1300938,
        optimizedBytes: 42864,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-57.webp",
        alt: "Restauração em resina - caso 57",
        originalName: "restauração  (73).png",
        originalBytes: 1216478,
        optimizedBytes: 33714,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-58.webp",
        alt: "Restauração em resina - caso 58",
        originalName: "restauração  (74).png",
        originalBytes: 1017025,
        optimizedBytes: 30896,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-59.webp",
        alt: "Restauração em resina - caso 59",
        originalName: "restauração  (75).png",
        originalBytes: 1234038,
        optimizedBytes: 40160,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-60.webp",
        alt: "Restauração em resina - caso 60",
        originalName: "restauração  (76).png",
        originalBytes: 1487516,
        optimizedBytes: 45650,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-61.webp",
        alt: "Restauração em resina - caso 61",
        originalName: "restauração  (77).png",
        originalBytes: 1544375,
        optimizedBytes: 50172,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-62.webp",
        alt: "Restauração em resina - caso 62",
        originalName: "restauração  (78).png",
        originalBytes: 1466483,
        optimizedBytes: 47822,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-63.webp",
        alt: "Restauração em resina - caso 63",
        originalName: "restauração  (79).png",
        originalBytes: 1503623,
        optimizedBytes: 55130,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-64.webp",
        alt: "Restauração em resina - caso 64",
        originalName: "restauração  (80).png",
        originalBytes: 1355006,
        optimizedBytes: 42848,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-65.webp",
        alt: "Restauração em resina - caso 65",
        originalName: "restauração  (81).png",
        originalBytes: 1398874,
        optimizedBytes: 40726,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-66.webp",
        alt: "Restauração em resina - caso 66",
        originalName: "restauração  (82).png",
        originalBytes: 1438984,
        optimizedBytes: 40482,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-67.webp",
        alt: "Restauração em resina - caso 67",
        originalName: "restauração  (83).png",
        originalBytes: 1432789,
        optimizedBytes: 46034,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-68.webp",
        alt: "Restauração em resina - caso 68",
        originalName: "restauração  (84).png",
        originalBytes: 1508690,
        optimizedBytes: 51294,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-69.webp",
        alt: "Restauração em resina - caso 69",
        originalName: "restauração  (85).png",
        originalBytes: 1423275,
        optimizedBytes: 42548,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-70.webp",
        alt: "Restauração em resina - caso 70",
        originalName: "restauração  (86).png",
        originalBytes: 1557071,
        optimizedBytes: 40958,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-71.webp",
        alt: "Restauração em resina - caso 71",
        originalName: "restauração  (92).png",
        originalBytes: 1092902,
        optimizedBytes: 37792,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-72.webp",
        alt: "Restauração em resina - caso 72",
        originalName: "restauração  (93).png",
        originalBytes: 996063,
        optimizedBytes: 37586,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-73.webp",
        alt: "Restauração em resina - caso 73",
        originalName: "restauração  (94).png",
        originalBytes: 1391666,
        optimizedBytes: 43946,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-74.webp",
        alt: "Restauração em resina - caso 74",
        originalName: "restauração  (95).png",
        originalBytes: 854753,
        optimizedBytes: 28408,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-75.webp",
        alt: "Restauração em resina - caso 75",
        originalName: "restauração  (96).png",
        originalBytes: 498136,
        optimizedBytes: 17082,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-76.webp",
        alt: "Restauração em resina - caso 76",
        originalName: "restauração  (97).png",
        originalBytes: 2411863,
        optimizedBytes: 41574,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-77.webp",
        alt: "Restauração em resina - caso 77",
        originalName: "restauraçao .png",
        originalBytes: 1356794,
        optimizedBytes: 30016,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-78.webp",
        alt: "Restauração em resina - caso 78",
        originalName: "restauração .png",
        originalBytes: 1064748,
        optimizedBytes: 32904,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-79.webp",
        alt: "Restauração em resina - caso 79",
        originalName: "restauração (2).png",
        originalBytes: 1922073,
        optimizedBytes: 38828,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-80.webp",
        alt: "Restauração em resina - caso 80",
        originalName: "restauração (3).png",
        originalBytes: 1650873,
        optimizedBytes: 29064,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-81.webp",
        alt: "Restauração em resina - caso 81",
        originalName: "restauração amalgama   (2).png",
        originalBytes: 937016,
        optimizedBytes: 25546,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-82.webp",
        alt: "Restauração em resina - caso 82",
        originalName: "restauração amalgama   (3).png",
        originalBytes: 1308753,
        optimizedBytes: 34500,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-83.webp",
        alt: "Restauração em resina - caso 83",
        originalName: "restauraçao em resina composta.png",
        originalBytes: 1906719,
        optimizedBytes: 39374,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-84.webp",
        alt: "Restauração em resina - caso 84",
        originalName: "restauraçao em resina estetica (2).png",
        originalBytes: 2248811,
        optimizedBytes: 41580,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-85.webp",
        alt: "Restauração em resina - caso 85",
        originalName: "restauraçao em resina estetica (3).png",
        originalBytes: 1580676,
        optimizedBytes: 24924,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-86.webp",
        alt: "Restauração em resina - caso 86",
        originalName: "restauraçao em resina estetica (4).png",
        originalBytes: 1643839,
        optimizedBytes: 26052,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-87.webp",
        alt: "Restauração em resina - caso 87",
        originalName: "restauraçao em resina estetica (5).png",
        originalBytes: 2153607,
        optimizedBytes: 41828,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-88.webp",
        alt: "Restauração em resina - caso 88",
        originalName: "restauraçao em resina estetica (6).png",
        originalBytes: 1608081,
        optimizedBytes: 35286,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-89.webp",
        alt: "Restauração em resina - caso 89",
        originalName: "restauraçao em resina estetica (7).png",
        originalBytes: 2054195,
        optimizedBytes: 42180,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-90.webp",
        alt: "Restauração em resina - caso 90",
        originalName: "restauraçao em resina estetica (12).png",
        originalBytes: 1474282,
        optimizedBytes: 26802,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-91.webp",
        alt: "Restauração em resina - caso 91",
        originalName: "restauraçao em resina estetica (14).png",
        originalBytes: 1392781,
        optimizedBytes: 27608,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-92.webp",
        alt: "Restauração em resina - caso 92",
        originalName: "restauraçao em resina estetica (15).png",
        originalBytes: 1774983,
        optimizedBytes: 30600,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-93.webp",
        alt: "Restauração em resina - caso 93",
        originalName: "restauraçao em resina estetica (16).png",
        originalBytes: 1939123,
        optimizedBytes: 38406,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-94.webp",
        alt: "Restauração em resina - caso 94",
        originalName: "restauraçao em resina estetica.png",
        originalBytes: 2179548,
        optimizedBytes: 40992,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-95.webp",
        alt: "Restauração em resina - caso 95",
        originalName: "Restauração.png",
        originalBytes: 1532957,
        optimizedBytes: 48538,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-96.webp",
        alt: "Restauração em resina - caso 96",
        originalName: "restauração(1).png",
        originalBytes: 2173069,
        optimizedBytes: 35682,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-97.webp",
        alt: "Restauração em resina - caso 97",
        originalName: "so para o doc (1).png",
        originalBytes: 1890258,
        optimizedBytes: 76232,
      },
      {
        src: "/site-assets/service-galleries/restauracao-em-resina/restauracao-em-resina-98.webp",
        alt: "Restauração em resina - caso 98",
        originalName: "so para o doc.png",
        originalBytes: 1497641,
        optimizedBytes: 46168,
      },
    ],
  },
] as const satisfies readonly ServiceGallery[]

export function getServiceGallery(slug: string) {
  return serviceGalleries.find((gallery) => gallery.slug === slug)
}

export function getServiceGalleriesByHref(href: string) {
  return serviceGalleries.filter((gallery) => gallery.serviceHref === href)
}
